
__include__: [
  'dataset/icip_detection.yml',
  'runtime/runtime.yml',
  'include/dataloader.yml',
  'include/optimizer.yml',
  'include/rtdetr_r50vd.yml',
  'preprocessing/default.yml'
]


output_dir: ./run_output

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


wandb:
  project_name: RT-DETR
  entity: petrychko-vitalii-ukrainian-catholic-university
  name: r18vd_6x_default

checkpoint_step: 10
seed: 1
