version: 1.0
preprocessing:
  out_channels: 3
  out_dim:
    - 640
    - 640
  pixel_size: 0.2506 # if set, images will be scaled to actual sizes in microns

paths:
  dataset_path: "data/dataset"

split:
  type: "stratified" # available: stratified
  ratio:
    - 0.8
    - 0.2
    - 0.0

filtering:
  label_statuses:
   - "Pending"
   - "Approved"
   - "Rejected"
   - "Approved automatically"
   - "Rejected automatically"
  categories:
    - name: "Paragonimus spp"
      train_set:
        use_empty_txt: false
        min_relative_area: 0
        max_relative_area: 1
        min_scaling_cf: 0.1
        max_scaling_cf: 10
      val_set:
        use_empty_txt: false
        min_relative_area: 0
        max_relative_area: 1
        min_scaling_cf: 0.1
        max_scaling_cf: 10
      test_set:
        use_empty_txt: false
        min_relative_area: 0
        max_relative_area: 1
        min_scaling_cf: 0.1
        max_scaling_cf: 10


